### ISSUE TITLE
slog new line format

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/toolbox#17]
Thank you very much for the error handling wrapper so that the code can be as concise as python. However, I found a problem that when the value of the slog is any, there is no line wrapping operation on the stack fetched by the errs package. I studied your code, and your stack handler writes line breaks, and when I go back to slog, I split them into lines with line breaks and remove spaces, and finally give them to value formatting. My attempt to force a line break inside the split stack slice still doesn't work, causing the multi-line stack to appear as a single line. Eventually I had to copy your code to make changes to make slog accept empty slices and print it directly where the logvalue is. I debugged the slog package related function and really didn't see the value of its wrapping slice type, which is weird. Do you have any suggestions?Once the line break is successful, I'll delete my changes and call your library directly. Thank you

**Comment by ddkwork** [comment]
https://github.com/richardwilkes/toolbox/blob/master/errs%2Flog.go#L126-L132

**Comment by ddkwork** [comment]
https://github.com/ddkwork/golibrary/blob/master/errs%2Flog.go#L126-L160

**Comment by ddkwork** [comment]
But the call log method of the call function has been written, and I'm going to call this eventually

https://github.com/richardwilkes/toolbox/blob/master/call.go#L18-L18

**Comment by ddkwork** [comment]
> You should probably be using my tracelog package to make use of the split lines. Here's how I initialize it when I use it:
> 
> ```
> slog.SetDefault(slog.New(tracelog.New(log.Default().Writer(), slog.LevelInfo)))
> ```

I will try, thx

**Comment by ddkwork** [comment]
> You should probably be using my tracelog package to make use of the split lines. Here's how I initialize it when I use it:
> 
> ```
> slog.SetDefault(slog.New(tracelog.New(log.Default().Writer(), slog.LevelInfo)))
> ```

Worked out, thanks. I have another proposal to rule out

[github.com/richardwilkes/toolbox.CallWithHandler]
 [github.com/richardwilkes/toolbox.Call]

Because it's the same every time it's triggered

https://github.com/ddkwork/golibrary/blob/master/errs%2Ferrors.go#L249-L250

**Comment by richardwilkes** [comment]
While the 3 additional things you're filtering out in the altered version of my code are indeed repetitive when encountered, when debugging I usually want to know that's how it got there. When you filter them out, you end up with magic gaps in the trace that may not be obvious to those not familiar with the code and how those functions operate.

That said, I am open to adding the option for clients to specify the set of prefixes they'd like to skip when the trimRuntime flag is set.

**Comment by ddkwork** [comment]
Nice work



---Original---
From: "Richard ***@***.***&gt;
Date: Tue, Apr 16, 2024 10:19 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [richardwilkes/toolbox] slog new line format (Issue #17)




 
While the 3 additional things you're filtering out in the altered version of my code are indeed repetitive when encountered, when debugging I usually want to know that's how it got there. When you filter them out, you end up with magic gaps in the trace that may not be obvious to those not familiar with the code and how those functions operate.
 
That said, I am open to adding the option for clients to specify the set of prefixes they'd like to skip when the trimRuntime flag is set.

**Comment by richardwilkes** [comment]
I just pushed this change. Enjoy!
